### ISSUE TITLE
[Suggestion] Add timer

### ISSUE THREAD

**Issue by Gabb1995** [tzhf/chatguessr#54]
Possible to add a timer widget (optional) which ends guesses automatically at the end of it.

**Comment by tzhf** [comment]
It's on the table 👍
Already made one in Vanilla but not entirely satisfied with it as we want something easily customizable with sound alerts, custom font colors and sizes, so it gets over complicated in pure Vanilla. We might want something like Svelte or Vue for that.

**Comment by tzhf** [comment]
Timer added in (https://github.com/tzhf/chatguessr/commit/e9ee9b2)

**Comment by tzhf** [comment]
Timer added in https://github.com/tzhf/chatguessr/commit/e9ee9b2

**Comment by tzhf** [comment]
Timer added in https://github.com/tzhf/chatguessr/commit/e9ee9b2
