### ISSUE TITLE
[Enhancement?] add support for webp flags

### ISSUE THREAD

**Issue by itsjustduc** [tzhf/chatguessr#59]
webp is a quite popular format on the web, and it would be convenient to be able to use them for flags. from what i can tell, the only change this would require is adding an extra line in this segment, as electron should support webp by default (as should the css background-url property):

https://github.com/tzhf/chatguessr/blob/48be88bee132a3f96b19a127c0d382bd941cb14e/src/utils/flags.js#L55-L59

where it gets rendered i think (for reference):

https://github.com/tzhf/chatguessr/blob/48be88bee132a3f96b19a127c0d382bd941cb14e/src/Classes/Scoreboard.js#L250-L259

this is not high priority, just thought i'd bring it up in case it's that simple to do. i also don't know if there are any other considerations to be made. it's not that hard to convert either way (for me, that is - plus my original reason for this was discord emojis, which are also available as png apparently D: ).

**Comment by tzhf** [comment]
Webp and other formats are now supported for custom flags: 4beb223
I haven't tested webp with the css backround image yet, but i guess it should work, still not a very common format tho
