### ISSUE TITLE
Can't login to twitch

### ISSUE THREAD

**Issue by jacobhamblin** [tzhf/chatguessr#69]
Going through the oauth flow doesn't result in a connected twitch account for me. I don't think my use case is unique, so I'm a bit confused.

Win 11, latest release from the website (3.0.2)

After 5 or so attempts, I added an exception in windows firewall for the executable in apps/local, no dice.

Here's how it looks for me:
![oauth](https://github.com/tzhf/chatguessr/assets/7588474/fdbf7928-9a0a-4587-bd26-0e23a889f674)

**Comment by jacobhamblin** [comment]
It eventually worked for me. Maybe because I filled in the streaming channel field? unsure

**Comment by tzhf** [comment]
Yes you need to fill your streaming channel. Sorry if it's a bit unclear, will make it more straightforward.
