### ISSUE TITLE
Repository of the backend or of the map

### ISSUE THREAD

**Issue by solodeveloping** [tzhf/chatguessr#72]
Hello,

First of all, this project is awesome, thanks a lot !

I was, maybe, thinking of adding a feature to the project, but I think it would require to modify the backend's map.

I asked in vinz's Discord, and he agreed with my statement that this repository does not contain the code of map.

I was wondering if you could indicate me (and the community) where is the repository of [the map](https://chatguessr.com/map/yourBot), and maybe the server.

I hope I'm not asking too much.

Have a good day,

**Comment by tzhf** [comment]
Just changed the repo's visibility to public :thumbsup: : https://github.com/tzhf/chatguessr-client

**Comment by solodeveloping** [comment]
With a delay, thank you for releasing the new repository :)

It's pretty awesome !

In the end, I decided to create my own alternative (the features I'ved made would have required a lot of coordinations).

It's still very much appreciated.
